

/gate/physics/addPhysicsList emstandard_opt3


# High cut by default
/gate/physics/Gamma/SetCutInRegion      world 1 km
/gate/physics/Electron/SetCutInRegion   world 1 km
/gate/physics/Positron/SetCutInRegion   world 1 km

# Cuts for particle in NEMACylinder
/gate/physics/Gamma/SetCutInRegion      phantom 1.0 mm
/gate/physics/Electron/SetCutInRegion   phantom 1.0 mm
/gate/physics/Positron/SetCutInRegion   phantom 1.0 mm

# Cuts for particle in LYSO
/gate/physics/Gamma/SetCutInRegion      LYSO 1.0 mm
/gate/physics/Electron/SetCutInRegion   LYSO 1.0 mm
/gate/physics/Positron/SetCutInRegion   LYSO 1.0 mm

# Cuts for particle in LuYAP-80
/gate/physics/Gamma/SetCutInRegion      LuYAP-80 1.0 mm
/gate/physics/Electron/SetCutInRegion   LuYAP-80 1.0 mm
/gate/physics/Positron/SetCutInRegion   LuYAP-80 1.0 mm
